---
output: 
  rmarkdown::pdf_document
thanks: ""
geometry: margin=1in
fontfamily: mathpazo
fontsize: 11pt
graphics: true
tables: true
---

```{r setup, include=FALSE}
# set this to FALSE to avoid errors in word-counting
echoCode <- TRUE
# set to TRUE to include figures within text or at the end (see endfloat package in template-file); this does not matter for supplementary figures which generated separately at the end of this file.
includeFigures <- TRUE


library(POUMM)
library(data.table)
library(ggplot2)
library(ape)
library(scales)
library(ggtree)
library(ggplot2)
library(lmtest)


collectSimulationData <- 
  function(simName, simType, treeName, treeInfo, execName, dataPath, ids=NULL) {
    
    load(paste0(dataPath, simName, "/", simName, ".RData"))
    
    # collect results
    data <- benchtable::collectBenchRes(
      "replication", data, dir.res = paste0(dataPath, simName, '/', execName), ids=ids)
    data[, simName:=simName]
    data[, simType:=simType]
    data[, treeName:=treeName]
    data[, treeInfo:=treeInfo]
  }

analyzeSimulationData <- function(
  data, 
  parNames = c('H2tMean', 'H2e', 'alpha', 'sigma', 'sigmae', 'g0', 'theta', 'H2tInf')) {
  
  extractFrom <- function(obj, name, method, what) {
    summaryShortMethod <- paste0("summaryShort", method)
    summaryExpertMethod <- paste0("summaryExpert", method)
    posteriorQuantileMethod <- paste0("posteriorQuantiles", method)
    if(name %in% parNames) {
      if(what == "value") {
        obj$parTrueFull[name]
      } else if(what == "MLE") {
        obj[[summaryShortMethod]][stat == name, estML[[1]] ]
      } else if(what == "HPDLower") {
        obj[[summaryShortMethod]][stat == name, HPD[[1]][1] ]
      } else if(what == "HPDUpper") {
        obj[[summaryShortMethod]][stat == name, HPD[[1]][2] ]
      } else if(what == "G.R.") {
        obj[[summaryShortMethod]][stat == name, G.R.[[1]] ]
      } else if(what == "MCMCBetterLik") {
        obj[[summaryExpertMethod]][['MCMCBetterLik']]
      } else if(what == "posteriorQuantile") {
        obj[[posteriorQuantileMethod]][[name]]
      }
    } 
  }
  
  towerData <- NULL
  
  for(name in parNames) {
    for(m in c("POUMM", "POUMMonG", "OU", "OUonG", "PMM")) {
      towerData <- rbindlist(list(
        towerData,
        data[sapply(replication, is.list), 
             list(
               id, 
               simName = simName, simType = simType, treeInfo = treeInfo,
               parameter = name, 
               value = sapply(replication, extractFrom, name, m, "value"),
               method = m,
               MLE = sapply(replication, extractFrom, name, m, "MLE"),
               HPDLower = sapply(replication, extractFrom, name, m, "HPDLower"),
               HPDUpper = sapply(replication, extractFrom, name, m, "HPDUpper"),
               posteriorQuantile = sapply(replication, extractFrom, name, m, 
                                          "posteriorQuantile"),
               G.R. = sapply(replication, extractFrom, name, m, "G.R."),
               MCMCBetterLik = sapply(replication, extractFrom, name, m, "MCMCBetterLik")
             )]
      ))  
    }
  }
  
  towerData
}


ggpl <- function(simulationType, treeInformation, methods = c("POUMM", "PMM")) {
  ggplot(
    data = simStats[
      simType %in% simulationType & treeInfo %in% treeInformation &
        method %in% methods & 
        parameter %in% c("H2tMean", "H2e", "H2tInf", "alpha", "g0", "theta", "sigma", "sigmae") &
        !sapply(G.R., is.na) & abs(G.R.-1) < .01]
    
  ) + 
    geom_histogram(aes(x = posteriorQuantile, y = ..density..), 
                   binwidth = 1/20, boundary=1/20)  +
    scale_y_continuous(name = "Density") + 
    coord_cartesian(ylim = c(0, 5)) +
    scale_x_continuous(breaks = c(0, .5, 1), labels = c("0", "0.5", "1"),
                       name = "Posterior quantiles") +
    facet_grid(simTypePretty + factor(methodPretty) ~ 
                 parameterPretty, 
               labeller = label_parsed) + 
    geom_text(
      data = simStatsSummary[
        simType %in% simulationType & treeInfo %in% treeInformation &
          method %in% methods & 
          parameter %in% c("H2tMean", "H2e", "H2tInf", "alpha", "g0", "theta", "sigma", "sigmae")], 
      aes(x = .42, y = 4.5, label = paste0("n=", n)), size = 3) + 
    geom_text(
      data = simStatsSummary[
        simType %in% simulationType & treeInfo %in% treeInformation &
          method %in% methods & 
          parameter %in% c("H2tMean", "H2e", "H2tInf", "alpha", "g0", "theta", "sigma", "sigmae")], 
      aes(x = .88, y = 4.4,
          label = factor(K.S.pValue < 0.01, labels = c(" ", "*")) ), 
      size = 4, col = "black")
  
}



AICc <- function(...) {
  objs <- list(...)
  sapply(objs, function(o) {
    aic <- AIC(o) 
    k <- length(coef(o))
    n <- nobs(o)
    aic + (2 * k * (k + 1)) / (n - k - 1)
  })
}


knitr::opts_chunk$set(dev = "pdf", dpi = 600,
  echo = FALSE, warning=FALSE, message=FALSE, 
  fig.path = "Manuscript-"
  )

```

<!-- Analysis of simulation data -->

```{r simInfo, include=FALSE}
dataPath <- "../tests/posterior-quantile-test/"

simInfo <- rbindlist(list(
  data.table(
    simName = c("Ultrametric_N4000_ATSSeG0",
                "NonUltrametric_N4000_ATSSeG0"),
    execName = c("exec_20170428",
                 "exec_20170428"),
    simType = c("POUMM", 
                "POUMM"),
    treeInfo = c("Sim. U (4000)",
                 "Sim. NU (4000)"),
    treeName = c("tree_bd_taxa_N4000_2_1_1",
                 "tree_bdsky_stt_N4000_2_1_1")
  ),
  data.table(
    simName = c("Ultrametric_N4000_ATSSeG0",
                "NonUltrametric_N4000_ATSSeG0"),
    execName = c("exec_PMM_20170428",
                 "exec_PMM_20170428"),
    simType = c("PMM", 
                "PMM"),
    treeInfo = c("Sim. U (4000)",
                 "Sim. NU (4000)"),
    treeName = c("tree_bd_taxa_N4000_2_1_1",
                 "tree_bdsky_stt_N4000_2_1_1")
  )))
```

```{r data, include=FALSE, eval=FALSE}
simData <- rbindlist(lapply(1:nrow(simInfo), function(simId) {
  simInfo[
    simId, 
    collectSimulationData(
      simName, simType, treeName, treeInfo, execName, dataPath)]
}))  
```

```{r simStats, include=FALSE, eval=FALSE}
simStats <- analyzeSimulationData(simData)

simStats[method %in% c('POUMMonG', 'OUonG'), simType:=ifelse(simType=="PMM", "BM", "OU")]
simStats[method=="OUonG", method:="OU"]
simStats[method=="POUMMonG", method:="POUMM"]

# At runtime the MCMC-samples of heritabilities ("H2e", "H2tMean", "H2tInf") were 
# compared to the value from the POUMM simulation but should have been compared
# to 1, since the OU-simulation do not included e.
simStats[simType=="OU" & method=="POUMM" & 
           parameter%in%c("H2e", "H2tMean", "H2tInf"), posteriorQuantile:=1]

# At runtime the MCMC-samples of theta from "OU" and "POUMM" inferences were 
# compared to the value from the PMM simulation but are irrelevant since the 
# value of theta is not taken into account in PMM simulations.
simStats[simType=="PMM" & (method %in% c("POUMM", "OU")) & parameter=="theta",
         posteriorQuantile:=NA]
simStats[simType=="PMM" & (method %in% c("POUMM", "OU")) & parameter=="theta",
         G.R.:=NaN]

save(simStats, file='../tests/posterior-quantile-test/simStats_20170428.RData')
```

```{r loadSimStats, include=FALSE, eval=TRUE}
load('../tests/posterior-quantile-test/simStats_20170428.RData')
simStats <- 
  simStats[
    , 
    list(id, simName, simType, treeInfo, parameter, value, method, 
         MLE, 
         HPDLower, HPDUpper, posteriorQuantile, G.R., MCMCBetterLik), 
    keyby = list(
      parameterPretty = factor(
        parameter,
        levels = c("H2tMean", "H2e", "H2tInf",  "g0", "theta",  "alpha", "sigma",  "sigmae", "rA", "b"),
        labels = c("H[bar(t)]^2",
                   "H[e]^2",
                   "H[infinity]^2",
                   "g[0]",
                   "theta",
                   "alpha",
                   "sigma",
                   "sigma[e]",
                   "r[A]",
                   "b")),
      methodPretty = factor(
        method,
        levels = c("POUMM", "PMM", "OU"),  #unique(method),
        labels = paste0("Infer~", c("POUMM", "PMM", "POU"))),
      simTypePretty = factor(
        simType,
        levels = c("POUMM", "OU", "PMM", "BM"),
        labels = c(expression("Simulate~POUMM"), expression("Simulate~POU"), expression("Simulate~PMM"), expression("Simulate~BM"))),
      treeInfoPretty = factor(
        treeInfo,
        levels = c("Sim. U (4000)", 
                   "Sim. NU (4000)"),
        labels = c("Ultr.~(BD~4000)",
                   "Non-ultr.~(BD~4000)"))
    )]

# summary statistics per parameter x scenario (for the moment, number of replications, 
# and Kolmogorov-Smirnov p-value from test for uniformity of the posterior quantiles)
simStatsSummary <- simStats[
  !sapply(G.R., is.na) & abs(G.R.-1) < .01,
  list(K.S.pValue = {
    if(sum(!is.na(posteriorQuantile))>0) {
      ks.test(posteriorQuantile, "punif")$p.value
    } else {
      as.double(NA)
    }},
    n = .N), 
  keyby = list(simName, simType, simTypePretty, 
               treeInfo, treeInfoPretty, 
               parameter, parameterPretty,
               method, methodPretty)]

```


```{r fig1, eval=TRUE, include=TRUE, results="hide",fig.width=6.2, fig.height=2.92}
newick <- "(((4:3,1:2.8)6:4.2,2:4.1)8:4.5,(5:4,3:5)7:6)9;"
tree <- read.tree(text=newick)

par(mfrow=c(1,5))
par(mar=c(0,0,0,0))
SPLITT::PlotParallelTraversal(tree, draw_prune_ranges = TRUE)
```

```{r fig-post-quantiles, results="hide", fig.width=6.75, fig.height=4.2, eval=TRUE}
simulationType = c("POUMM");
treeInformation = c("Sim. NU (4000)", "Sim. U (4000)"); 
methods = c("POUMM");

ggplot(
    data = simStats[
      simType %in% simulationType & treeInfo %in% treeInformation &
        method %in% methods & 
        parameter %in% c("alpha", "g0", "theta", "sigma", "sigmae") &
        !sapply(G.R., is.na) & abs(G.R.-1) < .01]
    
  ) + 
    geom_histogram(aes(x = posteriorQuantile, y = ..density..), 
                   binwidth = 1/20, boundary=1/20)  +
    scale_y_continuous(name = "Density") + 
    coord_cartesian(ylim = c(0, 5)) +
    scale_x_continuous(breaks = c(0, .5, 1), labels = c("0", "0.5", "1"),
                       name = "Posterior quantiles") +
    facet_grid(treeInfoPretty ~ 
                 parameterPretty, 
               labeller = label_parsed) + 
    geom_text(
      data = simStatsSummary[
        simType %in% simulationType & treeInfo %in% treeInformation &
          method %in% methods & 
          parameter %in% c("alpha", "g0", "theta", "sigma", "sigmae")], 
      aes(x = .42, y = 4.5, label = paste0("n=", n)), size = 3) + 
    geom_text(
      data = simStatsSummary[
        simType %in% simulationType & treeInfo %in% treeInformation &
          method %in% methods & 
          parameter %in% c("alpha", "g0", "theta", "sigma", "sigmae")], 
      aes(x = .88, y = 4.4,
          label = factor(K.S.pValue < 0.01, labels = c(" ")) ), 
      size = 4, col = "black")
  
```


<!-- Analyse microbenchmark data -->
```{r fig-plot-trees-N1000, include=TRUE, results = "hide", fig.width=6.7, fig.height=4, fig.cap="Tree topologies."}
#load("../../tests/benchmark/Trees.RData")
load("../tests/benchmark/Trees.RData")
library(ggtree)

pTypes <- c(p0.5="p = 0.5 (balanced)", 
            p0.1="p = 0.1", 
            p0.01="p = 0.01", 
            p.c99="p = 0.01/N (ladder)")

treeList <- lapply(
  trees[N==1000 & num_traits == 1, list(tree), keyby=pSymb][list(names(pTypes))]$tree, 
  function(tr) {
    tr$edge.length[] <- 1
    ladderize(tr)
  })

class(treeList) <- "multiPhylo"

ggtree(treeList, size = 0.1) + facet_wrap(~factor(sapply(.id, function(i) pTypes[i]), levels = pTypes), scales="free", ncol=4)
```

```{r merge-microbenchmark-data, include=FALSE, eval=TRUE}
files <- c("Results-microbenchmark-local-20171210.RData")
times1 <- rbindlist(lapply(files, function(f) {load(paste0("../tests/benchmark/", f)); times}))

times1[, order:="postorder"]
times1[sapply(as.character(expr), endsWith, "prune-ranges"), order:="range-based"] 
times1[sapply(as.character(expr), endsWith, "visit-ranges"), order:="visit-ranges"]
times1[sapply(as.character(expr), endsWith, "visit-queue"), order:="queue-based"]
times1[sapply(as.character(expr), endsWith, "split"), order:="split"]

times1[, Order:=factor(order, levels = c("postorder", "queue-based", "visit-ranges", "range-based", "split"))]

times1[, mode:="serial"]
times1[grep(".*parallel.*", as.character(expr)), mode:="parallel"]
times1[grep(".*hybrid.*", as.character(expr)), mode:="hybrid"]
times1[grep(".*auto.*", as.character(expr)), mode:="auto"]
times1[, Mode:=factor(mode, levels=c("serial", "parallel", "hybrid", "auto"))]

times1[, impl:="POUMM (C++)"]
times1[grep(".*abc.*", as.character(expr)), impl:="abc (C++)"]
times1[grep(".*diversitree: C.*", as.character(expr)), impl:="diversitree (C++)"]
times1[grep(".*diversitree: R.*", as.character(expr)), impl:="diversitree (R)"]
times1[grep(".*geiger.*", as.character(expr)), impl:="geiger (C++)"]
times1[, Implementation:=factor(impl, levels=c("POUMM (C++)", "lnDetV Q (C++)", "diversitree (R)", "diversitree (C++)", "geiger (C++)"))]

times1[, pUnbalanced:=factor(pSymb, levels=c("p0.5", "p0.1", "p0.01", "p.c99"), labels = c("p = 0.5  (balanced)", "p = 0.1", "p = 0.01", "p = 0.01/N (ladder)"))]

# times for the Rphylopars package running on MacBook Pro late 2013
files <- c("Result-9-RphyloparsMac-omp-1-blas-1.RData") 
times2 <- rbindlist(lapply(files, function(f) {load(paste0("../tests/benchmark/", f)); times}))
times2[, Computer:=factor("MacBookPro", levels = c("MacBookPro", "Euler"))]

# times for PCMBaseCpp package running on MacBook Pro late 2013
files <- c("Result-9-PCMBaseCppMac-omp-4-blas-1.RData") 
times3 <- rbindlist(lapply(files, function(f) {load(paste0("../tests/benchmark/", f)); times}))
times3[, Computer:=factor("MacBookPro", levels = c("MacBookPro", "Euler"))]

files <- c("Result-7-cluster-omp-1-blas-1.RData",
           "Result-7-cluster-omp-2-blas-1.RData",
           "Result-7-cluster-omp-4-blas-1.RData",
           "Result-7-cluster-omp-8-blas-1.RData",
           "Result-7-cluster-omp-12-blas-1.RData",
           "Result-7-cluster-omp-16-blas-1.RData",
           "Result-7-cluster-omp-20-blas-1.RData",
           "Result-7-cluster-omp-24-blas-1.RData")          

times4 <- rbindlist(lapply(files, function(f) {load(paste0("../tests/benchmark/", f)); times}))
times4[, Computer:=factor("Euler", levels = c("MacBookPro", "Euler"))]
# concatenate results for Rphylopars on MacBookPro with results from PCMBaseCpp on
# cluster
times4 <- rbindlist(list(times2, times3, times4)) 

times4[, id:=NULL]
times4[, order:="Quadratic polynomial"]
times4[sapply(impl, endsWith, "3-point"), order:="3-point"] 
times4[, Algorithm:=factor(order, levels = c("Quadratic polynomial", "3-point"))]

times4[, mode2:="serial"]
times4[grep(".*parallel queue.*", impl), mode2:="parallel queue"]
times4[grep(".*parallel range.*", impl), mode2:="parallel range except"]
times4[grep(".*parallel range no except.*", impl), mode2:="parallel range"]
times4[grep(".*hybrid range.*", impl), mode2:="hybrid range"]
times4[, Mode:=factor(mode2, levels=c("serial", "parallel queue", "parallel range except", "parallel range", "hybrid range"))]

times4[, package:="POUMM (C++)"]
times4[grep(".*PCMBase: C.*", impl), package:="PCMBaseCpp (C++)"]
times4[grep(".*PCMBase: R.*", impl), package:="PCMBase (R)"]
times4[grep(".*Rphylopars: C.*", impl), package:="Rphylopars (C++)"]
times4[grep(".*POUMM: R.*", impl), package:="POUMM (R)"]
times4[, Package:=factor(package, levels=c("POUMM (C++)", "PCMBaseCpp (C++)", "PCMBase (R)", "Rphylopars (C++)", "POUMM (R)"))]

times4[, pUnbalanced:=factor(pSymb, levels=c("p0.5", "p0.1", "p0.01", "p.c99"), labels = c("p = 0.5  (balanced)", "p = 0.1", "p = 0.01", "p = 0.01/N (ladder)"))]

times <- times4
```

```{r fig-plot-times, include=TRUE, results="hide", fig.width=6.75, fig.height=6.0, fig.cap="Likelihood calculation times for R and C++ implementations of the pruning algorithm.", include=includeFigures, eval=TRUE}
ggplot(times1[expr != "gc" & 
               type != "binary.with.star" &
               order != "split" & 
               order != "visit-ranges" &
               !sapply(impl, startsWith, "abc") &
               #!sapply(as.character(expr), endsWith, "split") &
               !mode %in% c("auto", "hybrid")
             ]) +
  geom_line(aes(x=N, y=mean, col=Implementation, linetype=Mode, shape=Order), size=0.3) +
  geom_point(aes(x=N, y=mean, col=Implementation, linetype=Mode, shape=Order), size = 0.9) +
  scale_shape_manual(values = c(`postorder`=20, `queue-based`=2, `range-based`=4, `prune-ranges`=22)) + 
  scale_y_continuous(limits = c(0.02, 4000), 
                     trans=log10_trans(), 
                     breaks = c(seq(0.02, 0.1, by=.04), 
                                seq(0.2, 1, by=.4), 
                                seq(2, 10, by=4), 
                                seq(20, 100, by=40),
                                seq(200, 1000, by=400), 
                                seq(2000, 10000, by=4000)),
                     minor_breaks = c(seq(0.04, 0.1, by=.4), 
                                      seq(0.4, 1, by=.4), 
                                      1.5,
                                      seq(4, 10, by=4), 
                                      15,
                                      seq(40, 100, by=40),
                                      150,
                                      seq(400, 1000, by=400),
                                      1500,
                                      seq(4000, 10000, by=4000),
                                      15000),
                     labels = comma) + 
  scale_x_continuous(limits = c(50, 2.6e5),
                     trans=log10_trans(), 
                     breaks = 10^(2:5), 
                     minor_breaks = NULL,
                     labels = comma) + 
  ggplot2::theme_grey() + 
  guides(linetype=guide_legend(order=1), 
         shape=guide_legend(ncol=2, order=2),
         col=guide_legend(ncol=2, order=3)) +
  theme(legend.position = "bottom", legend.direction = "vertical",
        axis.text = element_text(size = 6),
        axis.title = element_text(size = 8),
        panel.grid = element_line(size = 0.4),
        strip.text = element_text(size = 8, margin = margin(2, 0, 2, 0)),
        line = element_line(size=0.6)) +
  
  ylab("Time [ms]") +
  facet_grid(.~pUnbalanced)
```

```{r fig-plot-times-multivariate-MacBookPro, include=TRUE, results="hide", fig.width=6.75, fig.height=8.6, fig.cap="Multivariate likelihood calculation times on MacBookPro", include=includeFigures, eval=TRUE}
ggplot(times[
  Computer == "MacBookPro" &
    Package %in% c("Rphylopars (C++)", "PCMBaseCpp (C++)") & 
    Mode %in% c("serial", "parallel range")]) + 
  geom_line(
    aes(x=N, 
        y=time, 
        col=Package, 
        linetype=Mode
        ), size=0.3) +
  geom_point(
    aes(x=N, 
        y=time, 
        col=Package, 
        linetype=Mode
        ), size = 0.9) +
  scale_y_continuous(limits = c(0.6, 40000), 
                     trans=log10_trans(), 
                     breaks = c(seq(0.02, 0.1, by=.04), 
                                seq(0.2, 1, by=.4), 
                                seq(2, 10, by=4), 
                                seq(20, 100, by=40),
                                seq(200, 1000, by=400), 
                                seq(2000, 10000, by=4000),
                                seq(20000, 100000, by=40000)),
                     minor_breaks = c(seq(0.04, 0.1, by=.4), 
                                      seq(0.4, 1, by=.4), 
                                      1.5,
                                      seq(4, 10, by=4), 
                                      15,
                                      seq(40, 100, by=40),
                                      150,
                                      seq(400, 1000, by=400),
                                      1500,
                                      seq(4000, 10000, by=4000),
                                      15000,
                                      seq(40000, 100000, by=40000),
                                      150000),
                     labels = comma) + 
  scale_x_continuous(limits = c(50, 2.6e5),
                     trans=log10_trans(), 
                     breaks = 10^(2:5), 
                     minor_breaks = NULL,
                     labels = comma) + 
  scale_color_discrete(name = "Implementation") +
  scale_shape_discrete(name = "Number of traits") +
  scale_linetype_manual(values = c(serial = 1, `parallel range` = 2)) +
  ggplot2::theme_grey() + 
  guides(linetype=guide_legend(ncol=2, order=1), 
         #shape=guide_legend(ncol=2, order=2),
         col=guide_legend(ncol=2, order=3)) +
  theme(legend.position = "bottom", legend.direction = "vertical",
        axis.text = element_text(size = 6),
        axis.title = element_text(size = 8),
        panel.grid = element_line(size = 0.4),
        strip.text = element_text(size = 8, margin = margin(2, 0, 2, 0)),
        line = element_line(size=0.6)) +
  ylab("Time [ms]") +
  facet_grid(factor(k, levels = k, labels=(paste0("k=", k, " traits")))~pUnbalanced)
```


```{r fig-plot-times-euler-1, include=TRUE, results="hide", fig.width=6.7, fig.height=7.6, fig.cap="Likelihood calculation times for R and C++ implementations of multivariate OU caclulation."}

ggplot(times[
  Computer == "Euler" &
  #package=="PCMBaseCpp (C++)" &
  package=="POUMM (C++)" &
               !(Mode %in% c("parallel queue", 
                             "hybrid range", 
                             "parallel range except"
                             )) &
               #!pUnbalanced %in% c("p = 0.01/N (ladder)") &
               k == 1]) +
  geom_line(aes(x=omp_max_threads, y=time, 
                linetype=Mode), size = 0.3) +
  geom_point(aes(x=omp_max_threads, y=time, 
                 linetype=Mode), size = 0.6) +
  scale_y_continuous(labels = comma,
                     limits = c(0, NA)) + 
  scale_x_continuous(name = "Number of CPU cores",
                     limits = c(1, 24),
                     breaks = c(1, 2, seq(4, 24, by=4)),
                     minor_breaks = NULL,
                     labels = comma) +
  ggplot2::theme_grey() + 
  guides(linetype=guide_legend(order=1), 
         shape=guide_legend(ncol=1, order=2),
         col=guide_legend(ncol=2, order=3)) +
  theme(legend.position = "bottom", legend.direction = "horizontal",
        axis.text = element_text(size = 6),
        axis.title = element_text(size = 8),
        panel.grid = element_line(size = 0.4),
        strip.text = element_text(size = 8, margin = margin(2, 0, 2, 0)),
        line = element_line(size=0.6)) +
  
  ylab("Time [ms]") +
  facet_wrap(paste0("N = ",N)~pUnbalanced, scales="free")
```

```{r fig-plot-times-euler-multi-1, include=TRUE, results="hide", fig.width=6.7, fig.height=7.6, fig.cap="Likelihood calculation times for R and C++ implementations of multivariate OU caclulation."}

pl <- ggplot(times[
  Computer == "Euler" &
  package=="PCMBaseCpp (C++)" &
               !(Mode %in% c(
                             "hybrid range", 
                             "parallel range except"
                             )) &
               k == 1]) +
  geom_line(aes(x=omp_max_threads, y=time, 
                linetype=Mode), size = 0.3) +
  geom_point(aes(x=omp_max_threads, y=time, 
                 linetype=Mode), size = 0.6) +
  scale_y_continuous(labels = comma,
                     limits = c(0, NA)) + 
  scale_x_continuous(name = "Number of CPU cores",
                     limits = c(1, 24),
                     breaks = c(1, 2, seq(4, 24, by=4)),
                     minor_breaks = NULL,
                     labels = comma) +
  scale_linetype_manual(values = c(serial = 1, `parallel range` = 2, `parallel queue`=3)) +
  ggplot2::theme_grey() + 
  guides(linetype=guide_legend(order=1), 
         shape=guide_legend(ncol=1, order=2),
         col=guide_legend(ncol=2, order=3)) +
  theme(legend.position = "bottom", legend.direction = "horizontal",
        axis.text = element_text(size = 6),
        axis.title = element_text(size = 8),
        panel.grid = element_line(size = 0.4),
        strip.text = element_text(size = 8, margin = margin(2, 0, 2, 0)),
        line = element_line(size=0.6)) +
  
  ylab("Time [ms]") +
  facet_wrap(paste0("N = ",N)~pUnbalanced, scales="free")
```


```{r fig-plot-speedup-euler-1, include=TRUE, results="hide", fig.width=6.7, fig.height=7.6, fig.cap="Likelihood calculation times for R and C++ implementations of multivariate OU caclulation."}
ggplot(times[Computer == "Euler" & 
               k==1 & Package=="POUMM (C++)" & 
               Mode %in% c("serial", "parallel range", "parallel queue"),
             list(Mode, speedup=c(1, time[1]/time[-1])), 
             keyby=list(pUnbalanced, Algorithm, N, k, omp_max_threads)]) +
  geom_abline(aes(slope = 1, intercept = 0), linetype=1, size=0.3, color="darkgrey") +
  geom_abline(aes(slope = 0.5, intercept = 0), linetype=1, size=0.3, color="red") +
  geom_line(aes(x=omp_max_threads, y=speedup, 
                linetype=Mode), size=0.3) +
  geom_point(aes(x=omp_max_threads, y=speedup, 
                 linetype=Mode), size=0.6) +
  scale_y_continuous(labels = comma,
                     limits = c(0, 12),
                     breaks = c(1, 2, seq(4, 24, by=4)),
                     minor_breaks = NULL) + 
  scale_x_continuous(name = "Number of CPU cores",
                     limits = c(1, 24),
                     breaks = c(1, 2, seq(4, 24, by=4)),
                     minor_breaks = NULL,
                     labels = comma) +
  scale_linetype_manual(values = c(serial = 1, `parallel range`=2, `parallel queue`=3)) +
  ggplot2::theme_grey() + 
  guides(linetype=guide_legend(order=1), 
         shape=guide_legend(ncol=1, order=2),
         col=guide_legend(ncol=2, order=3)) +
  theme(legend.position = "bottom", legend.direction = "horizontal",
        axis.text = element_text(size = 6),
        axis.title = element_text(size = 8),
        panel.grid = element_line(size = 0.4),
        strip.text = element_text(size = 8, margin = margin(2, 0, 2, 0)),
        line = element_line(size=0.6)) +
  
  ylab("Parallel speedup [x]") +
  facet_wrap(paste0("N = ", N)~pUnbalanced, scales="free")
```

```{r fig-plot-speedup-euler-multi-1, include=TRUE, results="hide", fig.width=6.7, fig.height=7.6, fig.cap="Parallel speedup, Euler multivariate 1 trait."}
ggplot(times[Computer == "Euler" & 
               k==1 & Package=="PCMBaseCpp (C++)" & 
               Mode %in% c("serial", "parallel range", "parallel queue"),
             list(Mode, speedup=c(1, time[1]/time[-1])), 
             keyby=list(pUnbalanced, Algorithm, N, k, omp_max_threads)]) +
  geom_abline(aes(slope = 1, intercept = 0), linetype=1, size=0.3, color="darkgrey") +
  geom_abline(aes(slope = 0.5, intercept = 0), linetype=1, size=0.3, color="red") +
  geom_line(aes(x=omp_max_threads, y=speedup, 
                linetype=Mode), size=0.3) +
  geom_point(aes(x=omp_max_threads, y=speedup, 
                 linetype=Mode), size=0.6) +
  scale_y_continuous(labels = comma,
                     limits = c(0, 12),
                     breaks = c(1, 2, seq(4, 24, by=4)),
                     minor_breaks = NULL) + 
  scale_x_continuous(name = "Number of CPU cores",
                     limits = c(1, 24),
                     breaks = c(1, 2, seq(4, 24, by=4)),
                     minor_breaks = NULL,
                     labels = comma) +
  scale_linetype_manual(values = c(serial = 1, `parallel range`=2, `parallel queue`=3)) +
  ggplot2::theme_grey() + 
  guides(linetype=guide_legend(order=1), 
         shape=guide_legend(ncol=1, order=2),
         col=guide_legend(ncol=2, order=3)) +
  theme(legend.position = "bottom", legend.direction = "horizontal",
        axis.text = element_text(size = 6),
        axis.title = element_text(size = 8),
        panel.grid = element_line(size = 0.4),
        strip.text = element_text(size = 8, margin = margin(2, 0, 2, 0)),
        line = element_line(size=0.6)) +
  
  ylab("Parallel speedup [x]") +
  facet_wrap(paste0("N = ", N)~pUnbalanced, scales="free")
```

```{r fig-plot-times-euler-4, include=TRUE, results="hide", fig.width=6.7, fig.height=8.8, fig.cap="Likelihood calculation times for R and C++ implementations of multivariate OU caclulation."}
num_traits <- 4

ggplot(times[
  Computer == "Euler" &
  package %in% c("PCMBaseCpp (C++)", "Rphylopars (C++)") &
               !(Mode %in% c(
                             "hybrid range", 
                             "parallel range except"
                             )) &
                k == num_traits]) +
  geom_line(aes(x=omp_max_threads, y=time, 
                linetype=Mode), size=0.3) +
  geom_point(aes(x=omp_max_threads, y=time, 
                 linetype=Mode), size = 0.6) +
  scale_y_continuous(labels = comma, 
                     limits = c(0, NA)) + 
  scale_x_continuous(name = "Number of CPU cores",
                     limits = c(1, 20),
                     breaks = c(1, 2, seq(4, 20, by=4)),
                     minor_breaks = NULL,
                     labels = comma) +
  scale_linetype_manual(values = c(serial = 1, `parallel range` = 2, `parallel queue`=3)) +
  ggplot2::theme_grey() + 
  guides(linetype=guide_legend(order=1), 
         shape=guide_legend(ncol=1, order=2),
         col=guide_legend(ncol=2, order=3)) +
  theme(legend.position = "bottom", legend.direction = "vertical",
        axis.text = element_text(size = 6),
        axis.title = element_text(size = 8),
        panel.grid = element_line(size = 0.4),
        strip.text = element_text(size = 8, margin = margin(2, 0, 2, 0)),
        line = element_line(size=0.6)) +
  
  ylab("Time [ms]") +
  facet_wrap(N~pUnbalanced, scales="free")
```

```{r fig-plot-speedup-euler-4, include=TRUE, results="hide", fig.width=6.7, fig.height=7.6, fig.cap="Likelihood calculation times for R and C++ implementations of multivariate OU caclulation."}
num_traits <- 4
ggplot(times[
  Computer == "Euler" &
    k==num_traits & 
    Package=="PCMBaseCpp (C++)" & 
    Mode %in% c("serial", "parallel range", "parallel queue"), 
  list(Mode, speedup=c(1, time[1]/time[-1])), 
  keyby=list(pUnbalanced, Algorithm, N, k, omp_max_threads)]) +
  geom_abline(aes(slope = 1, intercept = 0), linetype=1, size=0.3, color="darkgrey") +
  geom_abline(aes(slope = 0.5, intercept = 0), linetype=1, size=0.3, color="red") +
  geom_line(aes(x=omp_max_threads, y=speedup, 
                linetype=Mode), size=0.3) +
  geom_point(aes(x=omp_max_threads, y=speedup, 
                 linetype=Mode), size=0.6) +
  scale_y_continuous(labels = comma,
                     limits = c(0, 12),
                     breaks = c(1, 2, seq(4, 24, by=4)),
                     minor_breaks = NULL) + 
  scale_x_continuous(name = "Number of CPU cores",
                     limits = c(1, 24),
                     breaks = c(1, 2, seq(4, 24, by=4)),
                     minor_breaks = NULL,
                     labels = comma) +
  scale_linetype_manual(values = c(serial = 1, `parallel range`=2, `parallel queue`=3)) +
  ggplot2::theme_grey() + 
  guides(linetype=guide_legend(order=1), 
         shape=guide_legend(ncol=1, order=2),
         col=guide_legend(ncol=2, order=3)) +
  theme(legend.position = "bottom", legend.direction = "horizontal",
        axis.text = element_text(size = 6),
        axis.title = element_text(size = 8),
        panel.grid = element_line(size = 0.4),
        strip.text = element_text(size = 8, margin = margin(2, 0, 2, 0)),
        line = element_line(size=0.6)) +
  
  ylab("Parallel speedup [x]") +
  facet_wrap(paste0("N = ", N)~pUnbalanced, scales="free")
```


```{r fig-plot-times-euler-8, include=TRUE, results="hide", fig.width=6.7, fig.height=8.8, fig.cap="Likelihood calculation times for R and C++ implementations of multivariate OU caclulation."}
num_traits <- 8

ggplot(times[
  Computer == "Euler" & 
  package %in% c("PCMBaseCpp (C++)", "Rphylopars (C++)") &
               !(Mode %in% c(
                             "hybrid range", 
                             "parallel range except"
                             )) &
               k == num_traits]) +
  geom_line(aes(x=omp_max_threads, y=time, 
                linetype=Mode), size=0.3) +
  geom_point(aes(x=omp_max_threads, y=time, 
                 linetype=Mode), size=0.6) +
  scale_y_continuous(labels = comma, 
                     limits = c(0, NA)) + 
  scale_x_continuous(name = "Number of CPU cores",
                     limits = c(1, 20),
                     breaks = c(1, 2, seq(4, 20, by=4)),
                     minor_breaks = NULL,
                     labels = comma) +
  scale_linetype_manual(values = c(serial = 1, `parallel range` = 2, `parallel queue`=3)) +
  ggplot2::theme_grey() + 
  guides(linetype=guide_legend(order=1), 
         shape=guide_legend(ncol=1, order=2),
         col=guide_legend(ncol=2, order=3)) +
  theme(legend.position = "bottom", legend.direction = "vertical",
        axis.text = element_text(size = 6),
        axis.title = element_text(size = 8),
        panel.grid = element_line(size = 0.4),
        strip.text = element_text(size = 8, margin = margin(2, 0, 2, 0)),
        line = element_line(size=0.6)) +
  
  ylab("Time [ms]") +
  facet_wrap(N~pUnbalanced, scales="free")
```

```{r fig-plot-speedup-euler-8, include=TRUE, results="hide", fig.width=6.7, fig.height=7.6, fig.cap="Likelihood calculation times for R and C++ implementations of multivariate OU caclulation."}
num_traits <- 8
ggplot(times[
  Computer == "Euler" & 
    k==num_traits & 
    Package=="PCMBaseCpp (C++)" & 
    Mode %in% c("serial", "parallel range", "parallel queue"), 
  list(Mode, speedup=c(1, time[1]/time[-1])), 
  keyby=list(pUnbalanced, Algorithm, N, k, omp_max_threads)]) +
  geom_abline(aes(slope = 1, intercept = 0), linetype=1, size=0.3, color="darkgrey") +
  geom_abline(aes(slope = 0.5, intercept = 0), linetype=1, size=0.3, color="red") +
  geom_line(aes(x=omp_max_threads, y=speedup, 
                linetype=Mode), size=0.3) +
  geom_point(aes(x=omp_max_threads, y=speedup, 
                 linetype=Mode), size=0.6) +
  scale_y_continuous(labels = comma,
                     limits = c(0, 12),
                     breaks = c(1, 2, seq(4, 24, by=4)),
                     minor_breaks = NULL) + 
  scale_x_continuous(name = "Number of CPU cores",
                     limits = c(1, 24),
                     breaks = c(1, 2, seq(4, 24, by=4)),
                     minor_breaks = NULL,
                     labels = comma) +
  scale_linetype_manual(values = c(serial = 1, `parallel range`=2, `parallel queue`=3)) +
  ggplot2::theme_grey() + 
  guides(linetype=guide_legend(order=1), 
         shape=guide_legend(ncol=1, order=2),
         col=guide_legend(ncol=2, order=3)) +
  theme(legend.position = "bottom", legend.direction = "horizontal",
        axis.text = element_text(size = 6),
        axis.title = element_text(size = 8),
        panel.grid = element_line(size = 0.4),
        strip.text = element_text(size = 8, margin = margin(2, 0, 2, 0)),
        line = element_line(size=0.6)) +
  
  ylab("Parallel speedup [x]") +
  facet_wrap(paste0("N = ", N)~pUnbalanced, scales="free")
```

```{r fig-plot-times-euler-16, include=TRUE, results="hide", fig.width=6.7, fig.height=8.8, fig.cap="Likelihood calculation times for R and C++ implementations of multivariate OU caclulation."}
num_traits <- 16

ggplot(times[
  Computer == "Euler" &
    package %in% c("PCMBaseCpp (C++)", "Rphylopars (C++)") &
    !(Mode %in% c(
      "hybrid range", 
      "parallel range except"
    )) &
    k == num_traits]) +
  geom_line(aes(x=omp_max_threads, y=time, 
                linetype=Mode), size=0.3) +
  geom_point(aes(x=omp_max_threads, y=time, 
                 linetype=Mode), size = 0.6) +
  scale_y_continuous(labels = comma, 
                     limits = c(0, NA)) + 
  scale_x_continuous(name = "Number of CPU cores",
                     limits = c(1, 20),
                     breaks = c(1, 2, seq(4, 20, by=4)),
                     minor_breaks = NULL,
                     labels = comma) +
  scale_linetype_manual(values = c(serial = 1, `parallel range` = 2, `parallel queue`=3)) +
  ggplot2::theme_grey() + 
  guides(linetype=guide_legend(order=1), 
         shape=guide_legend(ncol=1, order=2),
         col=guide_legend(ncol=2, order=3)) +
  theme(legend.position = "bottom", legend.direction = "vertical",
        axis.text = element_text(size = 6),
        axis.title = element_text(size = 8),
        panel.grid = element_line(size = 0.4),
        strip.text = element_text(size = 8, margin = margin(2, 0, 2, 0)),
        line = element_line(size=0.6)) +
  
  ylab("Time [ms]") +
  facet_wrap(N~pUnbalanced, scales="free")
```

```{r fig-plot-speedup-euler-16, include=TRUE, results="hide", fig.width=6.7, fig.height=7.6, fig.cap="Likelihood calculation times for R and C++ implementations of multivariate OU caclulation."}
num_traits <- 16
ggplot(times[
  Computer == "Euler" & 
    k==num_traits & 
    Package=="PCMBaseCpp (C++)" & 
    Mode %in% c("serial", "parallel range", "parallel queue"), 
  list(Mode, speedup=c(1, time[1]/time[-1])), 
  keyby=list(pUnbalanced, Algorithm, N, k, omp_max_threads)]) +
  geom_abline(aes(slope = 1, intercept = 0), linetype=1, size=0.3, color="darkgrey") +
  geom_abline(aes(slope = 0.5, intercept = 0), linetype=1, size=0.3, color="red") +
  geom_line(aes(x=omp_max_threads, y=speedup, 
                linetype=Mode), size=0.3) +
  geom_point(aes(x=omp_max_threads, y=speedup, 
                 linetype=Mode), size=0.6) +
  scale_y_continuous(labels = comma,
                     limits = c(0, 12),
                     breaks = c(1, 2, seq(4, 24, by=4)),
                     minor_breaks = NULL) + 
  scale_x_continuous(name = "Number of CPU cores",
                     limits = c(1, 24),
                     breaks = c(1, 2, seq(4, 24, by=4)),
                     minor_breaks = NULL,
                     labels = comma) +
  scale_linetype_manual(values = c(serial = 1, `parallel range`=2, `parallel queue`=3)) +
  ggplot2::theme_grey() + 
  guides(linetype=guide_legend(order=1), 
         shape=guide_legend(ncol=1, order=2),
         col=guide_legend(ncol=2, order=3)) +
  theme(legend.position = "bottom", legend.direction = "horizontal",
        axis.text = element_text(size = 6),
        axis.title = element_text(size = 8),
        panel.grid = element_line(size = 0.4),
        strip.text = element_text(size = 8, margin = margin(2, 0, 2, 0)),
        line = element_line(size=0.6)) +
  
  ylab("Parallel speedup [x]") +
  facet_wrap(paste0("N = ", N)~pUnbalanced, scales="free")
```


```{r table-time-create-cache, eval = FALSE}
tableCreateCache <- times1[type=="binary" & 
                             !is.na(timeCreateCache) & 
                             !sapply(Implementation, function(.) startsWith(as.character(.), 'ln')) & 
                             !Implementation=="diversitree (R)", 
                           list(timeCreateCache=min(timeCreateCache)), 
                          keyby=list(N, pSymb, Implementation)]

table <- rbindlist(lapply(10^{2:5}, function(NN) 
  tableCreateCache[N==NN, list(N=NN, Implementation=Implementation[pSymb=="p0.5"], 
                                `p=0.5`=.SD[pSymb=="p0.5", timeCreateCache*1000],
                                `p=0.1`=.SD[pSymb=="p0.1", timeCreateCache*1000],
                                `p=0.01`=.SD[pSymb=="p0.01", timeCreateCache*1000],
                                `p=0.01/N`=.SD[pSymb=="p.c99", timeCreateCache*1000]
                                )]
  
))

require(xtable)
xt <- xtable(table)
options(digits=6)
print(xt)
```


```{r load-hiv-mcmc-data, eval=TRUE, include=TRUE, results="hide"}
# no adaptation 1e6 iterations
#load("../tests/TestAdaptMCMCOnUKData/poumm1.RData")
#smm.poumm1 <- summary(poumm1, stat = c("alpha", "theta", "sigma", "sigmae", "g0"))
# adaptation during all 1e6 iterations
#load("../tests/TestAdaptMCMCOnUKData/poumm2.RData")
# adaptation during first 1e5 iterations out of 1e6 iterations
# load("../tests/TestAdaptMCMCOnUKData/poumm3.RData")
# no adaptation during 1e7 iterations
# load("../tests/TestAdaptMCMCOnUKData/poumm4.RData")

# smm.poumm3 <- summary(poumm3, thinMCMC=2000, mode="expert")
# smm.poumm4 <- summary(poumm4, thinMCMC=2000, mode="expert")
#save(smm.poumm3, smm.poumm4, file="../DATA/TestAdaptMCMCOnUKData/smm.poumm.RData")

# loads the two summary objects: smm.poumm3 and smm.poumm4. 
# 
load("../tests/TestAdaptMCMCOnUKData/smm.poumm.RData")

plots3 <- plot(smm.poumm3, stat = c("alpha", "theta", "sigma", "sigmae"), doPlot=FALSE)

plots4 <- plot(smm.poumm4, stat = c("alpha", "theta", "sigma", "sigmae"), doPlot=FALSE)
```

```{r fig-post-samples-hiv, include=TRUE, eval=TRUE, fig.width=6.75, fig.height=6.75}
cowplot::plot_grid(
  plots4$traceplot + 
    scale_x_continuous(name = "iteration", labels=scales::scientific, 
                       breaks = scales::pretty_breaks(n = 3)) +
    theme(legend.position = "none", axis.text=element_text(size=8)),
  plots3$traceplot + 
    scale_x_continuous(name = "iteration", labels=scales::scientific,
                       breaks = scales::pretty_breaks(n = 3)) +
    theme(legend.position = "none", axis.text=element_text(size=8)),
  plots4$densplot + theme(legend.position = "none", axis.text=element_text(size=8)),
  plots3$densplot + theme(legend.position = "none", axis.text=element_text(size=8)),
  nrow=2, ncol=2, 
  labels=c("a", "c", "b", "d"))
```

